### ISSUE TITLE
fix(security): Dot-Prop upgrade

### ISSUE THREAD

**Issue by learn2reid** [wwnorton/style#47]
https://github.com/wwnorton/style/network/alert/packages/commitlint-config-norton/package-lock.json/dot-prop/open

**Comment by ParmeJon** [comment]
This will be handled in the [norton-master-eslint](https://github.com/wwnorton/style/tree/norton-master-eslint) branch. I've updated @commitlint/config-conventional that resolves this dot-prop issue in this [commit](https://github.com/wwnorton/style/commit/62a6def787d283317943b28980b19ce0c6984fdc).
