### ISSUE TITLE
Docusaurus build breaking after updating to v2.0.0-alpha.63

### ISSUE THREAD

**Issue by ParmeJon** [wwnorton/style#55]
# 🐛  Docusaurus build breaking
Upon `npm run start` within the guides-website directory we receive an error:
```
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'id'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
```
I believe this issue is causing our github actions workflow for [deploying to gh-pages to fail](https://github.com/wwnorton/style/runs/1092831617?check_suite_focus=true). 

**To Reproduce**
1. Go to `guides-website` directory
2. Run `npm run start`
3. See error

**Expected behavior**
Docusaurus website is up and running with no errors.

**Seems to be an issue with the `docusaurus-plugin-sass` dependency not being compatible with Docusaurus versions greater than v2.0.0-alpha.61**

Related issue: https://github.com/facebook/docusaurus/issues/3361

**Comment by ParmeJon** [comment]
We can either:
1. downgrade Docusaurus version back to v2.0.0-alpha6.1
2. wait for the PR on `docusaurus-plugin-sass`
3. remove support for scss/sass in our guides-website

**Comment by learn2reid** [comment]
Thank's for catching this. Let's downgrade Docusaurus back to v2.0.0-alpha6.1 & wait for either the plugin or docusaurus itself to release a compatibility fix. Thanks
