### ISSUE TITLE
TypeScript: avoid export default

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/style#70]
**Is your feature request related to a problem? Please describe.**
The problem is best described in [Typescript Deep Dive - Avoid Export Default](https://basarat.gitbook.io/typescript/main-1/defaultisbad)

**Describe the solution you'd like**
This was in [beta.0 as a best practice](https://github.com/wwnorton/style/blob/v4.0.0-beta.0/src/rules/bestPractices.js) but was removed in a subsequent release. It should be part of the TypeScript rules but not part of the JavaScript rules.

Here are the required rules to accomplish this:

```js
rules: {
	/**
	 * Avoid export default to improve TypeScript experience. Applicable in
	 * JavaScript as well, though less impactful.
	 * For rationale, see https://basarat.gitbook.io/typescript/main-1/defaultisbad
	 */
	'import/prefer-default-export': 'off',
	'import/no-default-export': 'error',
},
```

**Describe alternatives you've considered**
N/A

**Additional context**
This may very well break things for other projects but I think it's worth including for the reasons outlined in the TypeScript Deep Dive (one of the best free books on TS).

**Comment by ParmeJon** [comment]
Hey @sh0ji, I read through that section in the Typescript Deep Dive. Makes sense to me with Typescript's autosuggest and autocomplete feature. I added a quick pull request to bring back the rules to avoid export default for the Typescript override entry-point. Let me know if you see any bugs.
